### ISSUE TITLE
Reboot won't connect

### ISSUE THREAD

**Issue by Arthur1967** [mrgsi/repository.topg#1]
Are you discontinuing this? I used it about a week and a half ago now it won't connect. It was a great little addition.

**Comment by Arthur1967** [comment]
I meant repo won't connect

**Comment by mrgsi** [comment]
That's odd, something must have broke. I will fix it today, thanks for letting me know.

**Comment by mrgsi** [comment]
Okay, one of the repositories inside recently changed it's url and broke the topg and freeg repos. I fixed the connections and updated both repos. If it isn't updating, just do another install from zip to force the update.

**Comment by Arthur1967** [comment]
OK I will try it. I just seen this. I am really looking for the zip for arctic Horizon. Thank you.

**Comment by Arthur1967** [comment]
I mean the original arctic Horizon

**Comment by Arthur1967** [comment]
Should I install your whole repo I only have top G tried it and it still won't connect

**Comment by mrgsi** [comment]
Make sure it's topg version 1.1.0. Artic Horizon is jurialmunkey's skin: https://github.com/jurialmunkey

**Comment by Arthur1967** [comment]
OK, thank you I'm gonna close this now but I still can't get the repo to work on nexus
